### PR TITLE
Allow mime 0.2

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by larsbergstrom** [comment]
@cybergeek94 Would it be possible to please land this and publish a new version to crates.io?

The need for this change is blocking Servo from moving beyond serde 0.6 to serde 0.7, which is limiting our ability to pick up changes in other projects that have already moved to that version. Thanks!

**Comment by cybergeek94** [comment]
Published as `1.5.1`, thanks @nox for the change!

**Comment by larsbergstrom** [comment]
@cybergeek94 Thanks much!

**Comment by cybergeek94** [comment]
This looks to have caused some back-compat issues (#17), so I'm yanking this and re-publishing as 1.6.

**Pull request merged**
